In [2]:
import numpy as np

Bài 1

In [5]:
print(np.zeros(shape=(10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Bài 2

Bài 3

In [9]:
print(np.arange(10, 51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Bài 4

In [12]:
print((np.arange(10, 51))[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Bài 5

In [13]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Bài 6

In [21]:
print(np.random.randint(100,size=(3,3)))

[[ 0 52 29]
 [33 58  2]
 [44 26 65]]


Bài 7

In [25]:
vecto7=np.random.randint(101,size=(10,10))
print(vecto7)
print(vecto7.max())
print(vecto7.min())

[[46 27  4 24 47 39 89 60  5  3]
 [55 89 13  1  5 53 99 82 75 34]
 [10 26 35 95 28 85 43 13 11 76]
 [ 9 48 12 92 57 99 60 85 74 90]
 [45 52 14 47  3 11 47 54 11 86]
 [40 99 90 94 82 42 74  5 51 14]
 [96 53  6 77 95  8 19 70 94  6]
 [ 9 95 45 95 81 60 49 87  1 24]
 [28 94  6 97 12  3 23 57 55 58]
 [29 81 25 72 87 16 95 51 70 62]]
99
1


Bài 8

In [26]:
vecto8=np.random.randint(101,size=(30))
print(vecto8)
print(vecto8.mean())

[30 51 32 98 14 16 99 80  4 14 62 57 94 60 25 69 11 40 88 92 75 57 32 23
 11 71 32 82 57 39]
50.5


Bài 9

In [31]:
x=5
y=5
matrix=np.array(shape=(x,y))
for i in range(x):
    for j in range(y):
        if i==0 or i==x-1 or j==0 or j==y-1:
            matrix[i][j]=1
        else:
            matrix[i][j]=0
print(matrix)

TypeError: array() missing required argument 'object' (pos 1)